# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - maven-google
      - gralde-plugin
      - gralde-jbdev

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

registries:
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
  gralde-plugin:
    type: maven-repository
    url: "https://plugins.gradle.org/m2/"
  gralde-jbdev:
    type: maven-repository
    url: "https://maven.pkg.jetbrains.space/public/p/compose/dev/"