name: Linux CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'README_EN.md'
      - 'LICENSE'

jobs:
  build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: 17
                distribution: 'temurin'
                cache: 'gradle'

            - name: Build
              run: bash ./gradlew packageReleaseDistributionForCurrentOS

            - name: Upload UpdaterKMM
              uses: actions/upload-artifact@v4
              with:
                name: UpdaterKMM-linux-x64-deb
                path: composeApp/build/compose/binaries/main-release/
                compression-level: 9